### ISSUE TITLE
Fichier migration

### ISSUE THREAD

**Issue by Skouat** [Sylver35/smiliescat#2]
https://github.com/Sylver35/smiliescat/blob/4b82004c18e47b9081ece9f4cccdd9f66bc08fe3/migrations/v110_schema.php#L26-L46

phpBB recommande de séparer update_data() de update_schema()
ref: https://area51.phpbb.com/docs/dev/3.3.x/extensions/tutorial_migrations.html

**Comment by Sylver35** [comment]
Fait, j'ai séparé les deux...
